<#
.SYNOPSIS
  Regenerates .env from existing Azure resources in a resource group.
#>
param(
    [Parameter(Mandatory = $true)]
    [string] $ResourceGroup,
    [switch] $ForceEnv
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "../..")
$envPath = Join-Path $repoRoot ".env"

if ((Test-Path $envPath) -and -not $ForceEnv) {
    throw ".env already exists. Use -ForceEnv to overwrite."
}

function Get-Resource([string] $Type) {
    az resource list --resource-group $ResourceGroup --resource-type $Type -o json | ConvertFrom-Json
}

$openAi = Get-Resource "Microsoft.CognitiveServices/accounts" | Where-Object { $_.kind -eq "OpenAI" } | Select-Object -First 1
$docInt = Get-Resource "Microsoft.CognitiveServices/accounts" | Where-Object { $_.kind -eq "FormRecognizer" } | Select-Object -First 1
$search = Get-Resource "Microsoft.Search/searchServices" | Select-Object -First 1
$storage = Get-Resource "Microsoft.Storage/storageAccounts" | Select-Object -First 1
$sb = Get-Resource "Microsoft.ServiceBus/namespaces" | Select-Object -First 1
$kv = Get-Resource "Microsoft.KeyVault/vaults" | Select-Object -First 1
$ai = Get-Resource "Microsoft.Insights/components" | Select-Object -First 1

if (-not $search -and -not $storage) {
    throw "No DevAssist resources found in resource group '$ResourceGroup'."
}

$openAiName = $openAi.name
$searchName = $search.name
$storageName = $storage.name
$docIntName = $docInt.name
$sbName = $sb.name
$kvName = $kv.name
$aiName = $ai.name

$openAiEndpoint = ""
$openAiKey = ""
if ($openAiName) {
    $openAiEndpoint = ((az cognitiveservices account show --name $openAiName --resource-group $ResourceGroup --query properties.endpoint -o tsv).TrimEnd("/")) + "/"
    $openAiKey = az cognitiveservices account keys list --name $openAiName --resource-group $ResourceGroup --query key1 -o tsv
}

$searchEndpoint = "https://$searchName.search.windows.net"
$searchKey = az search admin-key show --service-name $searchName --resource-group $ResourceGroup --query primaryKey -o tsv

$storageCs = az storage account show-connection-string --name $storageName --resource-group $ResourceGroup --query connectionString -o tsv

$docIntEndpoint = ""
$docIntKey = ""
if ($docIntName) {
    $docIntEndpoint = ((az cognitiveservices account show --name $docIntName --resource-group $ResourceGroup --query properties.endpoint -o tsv).TrimEnd("/")) + "/"
    $docIntKey = az cognitiveservices account keys list --name $docIntName --resource-group $ResourceGroup --query key1 -o tsv
}

$sbCs = ""
if ($sbName) {
    $sbCs = az servicebus namespace authorization-rule keys list `
        --resource-group $ResourceGroup `
        --namespace-name $sbName `
        --name RootManageSharedAccessKey `
        --query primaryConnectionString -o tsv
}

$kvUri = if ($kvName) { "https://$kvName.vault.azure.net/" } else { "" }

$appInsightsCs = ""
if ($aiName) {
    $appInsightsCs = az monitor app-insights component show --app $aiName --resource-group $ResourceGroup --query connectionString -o tsv
}

$searchSku = az search service show --name $searchName --resource-group $ResourceGroup --query sku.name -o tsv
$semantic = if ($searchSku -eq "standard") { "devassist-semantic" } else { "" }

$content = @"
# DevAssist AI Workspace — generated by scripts/azure/write-env.ps1
# Resource group: $ResourceGroup
# Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

ASPNETCORE_ENVIRONMENT=Development

ConnectionStrings__DevAssistDb=Server=localhost,14333;Database=DevAssistDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True

AzureOpenAi__Endpoint=$openAiEndpoint
AzureOpenAi__ApiKey=$openAiKey
AzureOpenAi__DeploymentName=gpt-4o
AzureOpenAi__EmbeddingDeploymentName=text-embedding-ada-002

AzureSearch__Endpoint=$searchEndpoint
AzureSearch__ApiKey=$searchKey
AzureSearch__IndexName=devassist-documents
AzureSearch__SemanticConfigurationName=$semantic
AzureSearch__VectorDimensions=1536

BlobStorage__ConnectionString=$storageCs
BlobStorage__ContainerName=documents

LocalFileStorage__RootPath=./data/documents

DocumentIntelligence__Endpoint=$docIntEndpoint
DocumentIntelligence__ApiKey=$docIntKey

ServiceBus__ConnectionString=$sbCs
ServiceBus__QueueName=devassist-indexing

KeyVault__Uri=$kvUri

ApplicationInsights__ConnectionString=$appInsightsCs

Jwt__Secret=devassist-local-jwt-secret-change-in-production-min-32-chars!!
Jwt__Issuer=devassist
Jwt__Audience=devassist
Jwt__DefaultAdminPassword=Admin@123!

AzureAd__TenantId=
AzureAd__ClientId=
AzureAd__Instance=https://login.microsoftonline.com/
AzureAd__Audience=

RateLimiting__GeneralPermits=100
RateLimiting__AiPermits=20
RateLimiting__WindowSeconds=60

Cors__AllowedOrigins__0=http://localhost:5173
Cors__AllowedOrigins__1=https://localhost:5173

VITE_API_BASE_URL=
VITE_AAD_CLIENT_ID=
VITE_AAD_TENANT_ID=
VITE_AAD_SCOPE=
"@

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($envPath, $content, $utf8)
Write-Host "Wrote $envPath" -ForegroundColor Green
