#!/usr/bin/env bash
# Regenerates .env from existing Azure resources in a resource group.
set -euo pipefail

RESOURCE_GROUP=""
FORCE_ENV=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
    --force-env) FORCE_ENV=true; shift ;;
    -h|--help)
      echo "Usage: $0 --resource-group NAME [--force-env]"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$RESOURCE_GROUP" ]]; then
  echo "--resource-group is required" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_PATH="$REPO_ROOT/.env"

if [[ -f "$ENV_PATH" && "$FORCE_ENV" != true ]]; then
  echo ".env already exists. Use --force-env to overwrite." >&2
  exit 1
fi

list_by_type() {
  az resource list --resource-group "$RESOURCE_GROUP" --resource-type "$1" -o json
}

OPENAI="$(list_by_type Microsoft.CognitiveServices/accounts | jq -r '.[] | select(.kind=="OpenAI") | .name' | head -1)"
DOCINT="$(list_by_type Microsoft.CognitiveServices/accounts | jq -r '.[] | select(.kind=="FormRecognizer") | .name' | head -1)"
SEARCH="$(list_by_type Microsoft.Search/searchServices | jq -r '.[0].name // empty')"
STORAGE="$(list_by_type Microsoft.Storage/storageAccounts | jq -r '.[0].name // empty')"
SB="$(list_by_type Microsoft.ServiceBus/namespaces | jq -r '.[0].name // empty')"
KV="$(list_by_type Microsoft.KeyVault/vaults | jq -r '.[0].name // empty')"
AI="$(list_by_type Microsoft.Insights/components | jq -r '.[0].name // empty')"

if [[ -z "$SEARCH" && -z "$STORAGE" ]]; then
  echo "No DevAssist resources found in '$RESOURCE_GROUP'." >&2
  exit 1
fi

OPENAI_ENDPOINT=""
OPENAI_KEY=""
if [[ -n "$OPENAI" ]]; then
  OPENAI_ENDPOINT="$(az cognitiveservices account show --name "$OPENAI" --resource-group "$RESOURCE_GROUP" --query properties.endpoint -o tsv)"
  OPENAI_ENDPOINT="${OPENAI_ENDPOINT%/}/"
  OPENAI_KEY="$(az cognitiveservices account keys list --name "$OPENAI" --resource-group "$RESOURCE_GROUP" --query key1 -o tsv)"
fi

SEARCH_ENDPOINT="https://${SEARCH}.search.windows.net"
SEARCH_KEY="$(az search admin-key show --service-name "$SEARCH" --resource-group "$RESOURCE_GROUP" --query primaryKey -o tsv)"
STORAGE_CS="$(az storage account show-connection-string --name "$STORAGE" --resource-group "$RESOURCE_GROUP" --query connectionString -o tsv)"

DOCINT_ENDPOINT=""
DOCINT_KEY=""
if [[ -n "$DOCINT" ]]; then
  DOCINT_ENDPOINT="$(az cognitiveservices account show --name "$DOCINT" --resource-group "$RESOURCE_GROUP" --query properties.endpoint -o tsv)"
  DOCINT_ENDPOINT="${DOCINT_ENDPOINT%/}/"
  DOCINT_KEY="$(az cognitiveservices account keys list --name "$DOCINT" --resource-group "$RESOURCE_GROUP" --query key1 -o tsv)"
fi

SB_CS=""
if [[ -n "$SB" ]]; then
  SB_CS="$(az servicebus namespace authorization-rule keys list \
    --resource-group "$RESOURCE_GROUP" \
    --namespace-name "$SB" \
    --name RootManageSharedAccessKey \
    --query primaryConnectionString -o tsv)"
fi

KV_URI=""
if [[ -n "$KV" ]]; then
  KV_URI="https://${KV}.vault.azure.net/"
fi

APPINSIGHTS_CS=""
if [[ -n "$AI" ]]; then
  APPINSIGHTS_CS="$(az monitor app-insights component show --app "$AI" --resource-group "$RESOURCE_GROUP" --query connectionString -o tsv)"
fi

SEARCH_SKU="$(az search service show --name "$SEARCH" --resource-group "$RESOURCE_GROUP" --query sku.name -o tsv)"
SEMANTIC=""
if [[ "$SEARCH_SKU" == "standard" ]]; then
  SEMANTIC="devassist-semantic"
fi

cat > "$ENV_PATH" <<EOF
# DevAssist AI Workspace — generated by scripts/azure/write-env.sh
# Resource group: $RESOURCE_GROUP
# Generated: $(date '+%Y-%m-%d %H:%M:%S')

ASPNETCORE_ENVIRONMENT=Development

ConnectionStrings__DevAssistDb=Server=localhost,14333;Database=DevAssistDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True

AzureOpenAi__Endpoint=$OPENAI_ENDPOINT
AzureOpenAi__ApiKey=$OPENAI_KEY
AzureOpenAi__DeploymentName=gpt-4o
AzureOpenAi__EmbeddingDeploymentName=text-embedding-ada-002

AzureSearch__Endpoint=$SEARCH_ENDPOINT
AzureSearch__ApiKey=$SEARCH_KEY
AzureSearch__IndexName=devassist-documents
AzureSearch__SemanticConfigurationName=$SEMANTIC
AzureSearch__VectorDimensions=1536

BlobStorage__ConnectionString=$STORAGE_CS
BlobStorage__ContainerName=documents

LocalFileStorage__RootPath=./data/documents

DocumentIntelligence__Endpoint=$DOCINT_ENDPOINT
DocumentIntelligence__ApiKey=$DOCINT_KEY

ServiceBus__ConnectionString=$SB_CS
ServiceBus__QueueName=devassist-indexing

KeyVault__Uri=$KV_URI

ApplicationInsights__ConnectionString=$APPINSIGHTS_CS

Jwt__Secret=devassist-local-jwt-secret-change-in-production-min-32-chars!!
Jwt__Issuer=devassist
Jwt__Audience=devassist
Jwt__DefaultAdminPassword=Admin@123!

AzureAd__TenantId=
AzureAd__ClientId=
AzureAd__Instance=https://login.microsoftonline.com/
AzureAd__Audience=

RateLimiting__GeneralPermits=100
RateLimiting__AiPermits=20
RateLimiting__WindowSeconds=60

Cors__AllowedOrigins__0=http://localhost:5173
Cors__AllowedOrigins__1=https://localhost:5173

VITE_API_BASE_URL=
VITE_AAD_CLIENT_ID=
VITE_AAD_TENANT_ID=
VITE_AAD_SCOPE=
EOF

echo "Wrote $ENV_PATH"
